set_languages("c++23")
add_rules("mode.debug", "mode.release")
add_requires("opencv", "vulkan-loader")
add_requires("imgui", {configs = {glfw = true, vulkan = true}})

target("Bleach-Brave-Souls-Bot")
    set_kind("binary")
    add_files("src/*.cpp")
    add_syslinks("user32")
    add_packages("opencv", "imgui", "vulkan-loader")
    add_defines("NOMINMAX")

    after_build(function (target)
            local asset_dir = path.join(target:targetdir(), "assets")
                os.mkdir(asset_dir)
                os.cp("assets/*", asset_dir)
    end)