set_languages("c++23")
add_rules("mode.debug", "mode.release")
add_requires("opencv", "vulkan-loader")
add_requires("imgui 1.92.9-docking", {configs = {glfw = true, vulkan = true}})

target("Bleach-Brave-Souls-Bot")
    set_kind("binary")
    add_files("src/*.cpp")
    add_syslinks("user32")
    add_packages("opencv", "imgui", "vulkan-loader")
    add_defines("NOMINMAX")

    after_build(function (target)
            local assetDirectory = path.join(target:targetdir(), "assets")
                os.mkdir(assetDirectory)
                os.cp("assets/*", assetDirectory)
    end)